limit_req_zone $binary_remote_addr zone=letterMailSendingLimit:10m rate=5r/m;

server {
	listen 80;
	listen [::]:80;
	server_name amnesty.marmelab.com;
	return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    server_name amnesty.marmelab.com;

    add_header   X-UA-Compatible "IE=edge";
    add_header   X-Frame-Options "SAMEORIGIN";

    ssl on;
    ssl_certificate /etc/nginx/conf.d/fullchain.pem;
    ssl_certificate_key /etc/nginx/conf.d/privkey.pem;

    location / {
        alias /app/front/build/;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/ua/ {
        if ($http_user_agent ~* ".*((T|t)witterbot)|((F|f)aceb(ook|ot))|((T|t)elegrambot).*") {
            proxy_pass http://api:4000/api/metadata$uri$is_args$args;
        }

        alias /app/front/build/;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location ^((\/fonts|\/static)(\/?.*))|(candle.svg|favicon.ico|global.css)$ {
        expires 30d;
        add_header Vary Accept-Encoding;
    }

    location /admin/ {
        alias /app/admin/build/;
    }

    location /api {
        proxy_pass http://api:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /api/static/ {
        alias /app/uploads/;
        expires 30d;
        add_header Vary Accept-Encoding;
    }

    location /api/ {
        proxy_pass http://api:4000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location ~ ^\/api\/.*\.pdf$ {
        proxy_pass http://api:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location ~ ^\/api\/.*\/send$ {
        limit_req zone=letterMailSendingLimit burst=10 nodelay;

        proxy_pass http://api:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /storybook/ {
        alias /app/front/storybook/;
    }

    error_log stderr;
    access_log stdout;
}
