limit_req_zone $binary_remote_addr zone=letterMailSendingLimit:10m rate=5r/m;

server {
	listen 80;
	listen [::]:80;
	server_name amnesty.marmelab.com;
	return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    server_name amnesty.marmelab.com;

    add_header   X-UA-Compatible "IE=edge";
    add_header   X-Frame-Options "SAMEORIGIN";

    ssl on;
    ssl_certificate /etc/nginx/conf.d/selfsigned.crt;
    ssl_certificate_key /etc/nginx/conf.d/selfsigned.key;

    location / {
        alias /app/front/build/;
    }

    location /admin {
        alias /app/admin/build/;
    }

    location /api {
        proxy_pass http://api:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /api/static {
        alias /app/uploads/;
    }

    location /api/ {
        proxy_pass http://api:4000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location ~ ^\/api\/.*\.pdf$ {
        proxy_pass http://api:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location ~ ^\/api\/.*\/send$ {
        limit_req zone=letterMailSendingLimit burst=10 nodelay;

        proxy_pass http://api:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /storybook {
        alias /app/front/storybook/;
    }

    error_log stderr;
    access_log stdout;
}
