stages:
  - build
  - deploy

variables:
  BROWSERSLIST_IGNORE_OLD_DATA: 'true'
  # don't treat warnings as errors
  CI: 'false'

.build: &build
  image: node:18
  tags:
    - yarn
  stage: build
  script:
    - node .yarn/releases/yarn-3.2.1.cjs --version
    - .clevercloud/static/build.sh
    - echo "transfer the compiled files"
    - cp --recursive front/build/ dist/
    - cp --recursive admin/build/ dist/admin/
    - cp .clevercloud/static/.htaccess dist/
    # the directory must exist
    - ls -lh ${PWD}/dist/
  artifacts:
    paths:
      - dist/
    expire_in: 24 hrs
    when: always

build_static_release:
  <<: *build
  variables:
    REF: $CI_COMMIT_REF_SLUG
    NODE_ENV: production
    REACT_APP_NODE_ENV: production
    FRONT_PUBLIC_URL: https://release.urgent.amnesty.fr
    ADMIN_PUBLIC_URL: https://release.urgent.amnesty.fr/admin
    REACT_APP_API_URL: https://release.rapide.amnesty.fr
    REACT_APP_FRONT_BASE_URL: https://release.urgent.amnesty.fr
    UPLOAD_URL: https://release.rapide.amnesty.fr/api/static
  only:
    - develop

build_static_prod:
  <<: *build
  variables:
    REF: $CI_COMMIT_REF_SLUG
    NODE_ENV: production
    REACT_APP_NODE_ENV: production
    FRONT_PUBLIC_URL: https://urgent.amnesty.fr
    ADMIN_PUBLIC_URL: https://urgent.amnesty.fr/admin
    REACT_APP_API_URL: https://rapide.amnesty.fr
    REACT_APP_FRONT_BASE_URL: https://urgent.amnesty.fr
    UPLOAD_URL: https://rapide.amnesty.fr/api/static
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches

##### Deploy #####
deploy_api_release:
  image:
    name: clevercloud/clever-tools:latest
    entrypoint: [ "/bin/sh", "-c" ]
  stage: deploy
  cache: [ ]
  script: |
    clever link ${APP_ID}
    clever deploy
  variables:
    APP_ID: app_eff241f8-4f37-48c9-bbb5-233a8d4a4a0b
  only:
    - develop
  environment:
    name: release_api
    url: https://release.rapide.amnesty.fr

deploy_api_prod:
  image:
    name: clevercloud/clever-tools:latest
    entrypoint: [ "/bin/sh", "-c" ]
  stage: deploy
  cache: [ ]
  script: |
    clever link ${APP_ID}
    clever deploy
  variables:
    APP_ID: app_34694fec-6a00-4c07-a001-6dac13102615
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches
  environment:
    name: prod_api
    url: https://rapide.amnesty.fr

.upload: &upload
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add --no-cache lftp
    - ls -lh ${PWD}/${DIRECTORY}
  script:
    # source: https://savjee.be/blog/gitlab-ci-deploy-to-ftp-with-lftp/
    - lftp -e "open ${FTP_HOST}; user ${FTP_USER} ${FTP_PASSWORD}; mirror --reverse --no-perms --verbose --delete ${DIRECTORY} /; bye"

upload_static_content_release:
  <<: *upload
  dependencies: ['build_static_release']
  needs: ['build_static_release']
  variables:
    DIRECTORY: 'dist/'
  script:
    # source: https://savjee.be/blog/gitlab-ci-deploy-to-ftp-with-lftp/
    - lftp -e "open ${DEVELOP_FTP_HOST}; user ${DEVELOP_FTP_USER} ${DEVELOP_FTP_PASSWORD}; mirror --reverse --no-perms --verbose --delete ${DIRECTORY} /; bye"
  only:
    - develop
  environment:
    name: release_static
    url: https://release.urgent.amnesty.fr

upload_static_content_prod:
  <<: *upload
  dependencies: ['build_static_prod']
  needs: ['build_static_prod']
  variables:
    DIRECTORY: 'dist/'
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches
  environment:
    name: prod_static
    url: https://urgent.amnesty.fr
