language: node_js
sudo: required

services:
    - docker

node_js:
    - '9.11.1'

install:
    - make install

cache:
    yarn: true
    directories:
        - node_modules
        - /tmp/amnesty

script:
    - make test

stages:
    - name: test
    - name: deploy

jobs:
    include:
        - stage: test
          env: NODE_ENV=test
        - stage: deploy
          env: NODE_ENV=staging
          script: skip
          deploy:
              skip_cleanup: true
              provider: script
              script: make deploy-staging
              on:
                  branch: master
