language: node_js
sudo: required

services:
    - docker

node_js:
    - '9.11.1'

install:
    - make install

cache:
    yarn: true
    directories:
        - node_modules
        - /tmp/amnesty

stages:
    - name: test

jobs:
    include:
        - stage: test
          env: NODE_ENV=test
          script:
              - make test-unit
        - stage: test
          env: NODE_ENV=test
          script:
              - make test-e2e
