version: '3'

services:
    api:
        command: 'yarn run start'
        environment:
            - NODE_ENV=staging
            - POSTGRES_PASSWORD
            - CORS_ALLOWED_ORIGIN="https://amnesty.marmelab.com"
            - UPLOAD_DIR=/app/uploads
            - UPLOAD_URL=https://amnesty.marmelab.com/api/static
            - SMTP_HOST
            - SMTP_USER
            - SMTP_PASSWORD
            - SMTP_PORT
            - SMTP_SERVICE
            - SF_BASE_URL
            - SF_API_VERSION
            - SF_CONSUMER_KEY
            - SF_CONSUMER_SECRET
            - SF_USERNAME
            - SF_PASSWORD
            - SF_SECURITY_TOKEN
        volumes:
            - /home/ubuntu/amnesty/uploads:/app/uploads

    nginx:
        image: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - .:/app
            - ./var/nginx/staging.conf:/etc/nginx/conf.d/default.conf
            - /home/ubuntu/amnesty/uploads:/app/uploads
            - /etc/letsencrypt/live/amnesty.marmelab.com/fullchain.pem:/etc/nginx/conf.d/selfsigned.crt
            - /etc/letsencrypt/live/amnesty.marmelab.com/privkey.pem:/etc/nginx/conf.d/selfsigned.key
        command:
            [sh, -c, "chmod -R o+X /app; chmod -R o+r /app/admin/build/; nginx -g 'daemon off;'"]
        depends_on:
            - api

    db:
        environment:
            - POSTGRES_USER=amnesty
            - POSTGRES_PASSWORD
            - POSTGRES_DB=reaction-rapide
        volumes:
            - '~/amnesty/data:/var/lib/postgresql/data/'
