version: "3"

services:
  documentation:
    image: ghcr.io/incaya/incaya-documentation:latest
    environment:
      - HUGO_PORT=1500
    volumes:
      - ./documentation:/documentation/content:rw
      - ./documentation-config/logo.jpg:/documentation/static/images/logo.jpg
      - ./documentation-config/hugo-config.toml:/documentation/config.toml
    user: "${UID}:${GID}"
    ports:
      - 1500:1500
      - 1501:3000

  db:
    image: postgres:10
    volumes:
      - amnesty-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=amnesty
      - POSTGRES_PASSWORD=amnesty
      - POSTGRES_DB=reaction-rapide
      - PGDATA=/var/lib/postgresql/data/amnesty
    ports:
      - "5432:5432"

  app:
    image: node:18.15.0-buster
    command: "npm run dev"
    working_dir: /app
    volumes:
      - "./next:/app"
      - "./uploads:/uploads"
    environment:
      - POSTGRES_USER=amnesty
      - POSTGRES_PASSWORD=amnesty
      - POSTGRES_DB=reaction-rapide
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    ports:
      - "3333:3333"

volumes:
  amnesty-postgres-data: {}
