version: '3'

services:
    admin:
        image: node:18
        user: '${UID}:${GID}'
        command: 'yarn run start'
        working_dir: /app/admin
        volumes:
            - '.:/app'
            - '/tmp:/tmp'
            - '~/.cache/.yarn/:/tmp/.cache/.yarn/'
            - '~/.npm/:/tmp/.npm/'
            - '~/.yarn/:/tmp/.yarn/'
        environment:
            - PORT=5000
            - NODE_ENV=development
            - HOME=/tmp
            - REACT_APP_API_URL=http://localhost:4000
            - REACT_APP_FRONT_BASE_URL=http://localhost:3000
        ports:
            - '5000:5000'

    maildev:
        image: djfarrelly/maildev
        expose:
            - '25'
        ports:
            - '1080:80'

    api:
        user: '${UID}:${GID}'
        command: 'yarn run start-dev'
        environment:
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=password
            - JWT_SECRET_KEY=foobarS3CR3T!
            - SMTP_HOST=maildev
            - SMTP_PORT=25
            - SMTP_IGNORE_TLS=true
            - SMTP_USER=
            - API_PREFIX_URL=
            - PM2_HOME=.pm2
            - SF_BASE_URL
            - SF_API_VERSION
            - SF_CONSUMER_KEY
            - SF_CONSUMER_SECRET
            - SF_USERNAME
            - SF_PASSWORD
            - SF_SECURITY_TOKEN
            - REACT_APP_API_URL=http://localhost:4000
        ports:
            - '4000:4000'

    db:
        volumes:
            - amnesty-postgres-data:/var/lib/postgresql/data
        user: '${UID}:${GID}'
        environment:
            - POSTGRES_USER=amnesty
            - POSTGRES_PASSWORD=amnesty
            - POSTGRES_DB=reaction-rapide
            - PGDATA=/var/lib/postgresql/data/amnesty

    storybook:
        image: node:12
        user: '${UID}:${GID}'
        command: 'yarn run storybook'
        working_dir: /app
        volumes:
            - './front:/app'
            - '/tmp:/tmp'
        environment:
            - NODE_ENV=development
        ports:
            - '9009:9009'

    front:
        image: node:18
        user: '${UID}:${GID}'
        command: 'yarn run start-web'
        working_dir: /app/front
        volumes:
            - '.:/app'
            - '/tmp:/tmp'
            - '~/.cache/.yarn/:/tmp/.cache/.yarn/'
            - '~/.npm/:/tmp/.npm/'
            - '~/.yarn/:/tmp/.yarn/'
        environment:
            - HOME=/tmp
            - REACT_APP_API_URL=http://localhost:4000
            - REACT_APP_GA=UA-136476291-2
            - REACT_APP_FB=2385476921667035
            - NODE_ENV=development
        ports:
            - '3000:3000'

    nginx:
        image: nginx:1.21
        ports:
            - '80:80'
        volumes:
            - ./var/uploads:/usr/share/nginx/html
        command: [sh, -c, "chmod -R o+X /app; nginx -g 'daemon off;'"]
volumes:
    amnesty-postgres-data: {}
