version: '3'

services:
    test:
        image: node:9
        working_dir: /app
        volumes:
            - "./:/app"
        environment:
            NODE_ENV: test
            POSTGRES_DATABASE: reaction-rapide-test
            ADMIN_USERNAME: admin
            ADMIN_PASSWORD: password
            JWT_SECRET_KEY: foobarS3CR3T
        command: npm run test

    api:
        command: "npm run start-dev"
        environment:
            NODE_ENV: test
            POSTGRES_DATABASE: reaction-rapide-test

    db:
        volumes:
            - "./var/data-test:/var/lib/postgresql/data/"
        environment:
            POSTGRES_USER: amnesty
            POSTGRES_PASSWORD: amnesty
            POSTGRES_DB: reaction-rapide-test
