version: '3'

services:
    api:
        command: "npm run start-dev"

    db:
        volumes:
            - "./var/data:/var/lib/postgresql/data/"
        environment:
            - POSTGRES_USER=amnesty
            - POSTGRES_PASSWORD=amnesty
            - POSTGRES_DB=reaction-rapide
