version: '3'

services:
    hub:
        image: selenium/hub:2.53.0

    chrome:
        image: selenium/node-chrome:2.53.0
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
        depends_on:
            - hub
        links:
            - hub
            - front
            - api

    chromedebug:
        image: selenium/node-chrome-debug:2.53.0
        links:
            - hub
            - front
            - api
        ports:
            - 5900:5900

    test-e2e:
        image: node:9
        links:
            - hub
            - front
            - api
        depends_on:
            - hub
            - chrome
        environment:
            NODE_ENV: test
        command: npm run test-e2e
        volumes:
            - ./front:/app
        working_dir: /app

    front:
        command: "npm run start-web"
        environment:
            - REACT_APP_API_URL=http://localhost:4000/
            - NODE_ENV=development

    api:
        command: npm run start-dev
        environment:
            NODE_ENV: development
            POSTGRES_DATABASE: reaction-rapide-test
