version: '3'

services:
    install:
        image: node:18
        user: '${UID}:${GID}'
        command: 'yarn'
        working_dir: /app/
        volumes:
            - '.:/app'
            - '/tmp:/tmp'
            - '~/.cache/.yarn/:/tmp/.cache/.yarn/'
            - '~/.npm/:/tmp/.npm/'
            - '~/.yarn/:/tmp/.yarn/'
        environment:
            - NODE_ENV=development
            - HOME=/tmp
