version: '3'

services:
    api:
        image: node:18
        working_dir: /app/api
        volumes:
            - '.:/app'
            - './config:/app/config'
            - '/tmp:/tmp'
            - '~/.cache/.yarn/:/tmp/.cache/.yarn/'
            - '~/.npm/:/tmp/.npm/'
            - '~/.yarn/:/tmp/.yarn/'
        environment:
            - NODE_ENV=development
            - HOME=/tmp
            - ADMIN_USERNAME
            - ADMIN_PASSWORD
            - JWT_SECRET_KEY
        depends_on:
            - db

    db:
        image: postgres:10
        volumes:
            - '/etc/passwd:/etc/passwd:ro'
        ports:
            - '5432:5432'
