version: '3'

services:
    admin:
        image: node:9
        command: "npm run start"
        volumes:
            - "./admin:/app"
            - "/tmp:/tmp"
        environment:
            - PORT=5000
            - NODE_ENV=development
            - HOME=/tmp
            - REACT_APP_API_URL=http://localhost:4000
            - REACT_APP_FRONT_BASE_URL=http://localhost:3000
        ports:
            - "5000:5000"
        working_dir: /app
        user: "${UID}:${GID}"

    api:
        command: "npm run start-dev"
        environment:
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=password
            - JWT_SECRET_KEY=foobarS3CR3T!
        ports:
            - "4000:4000"

    db:
        volumes:
            - "./var/data:/var/lib/postgresql/data/"
        environment:
            - POSTGRES_USER=amnesty
            - POSTGRES_PASSWORD=amnesty
            - POSTGRES_DB=reaction-rapide

    storybook:
        image: node:9
        command: "npm run storybook"
        volumes:
            - "./front:/app"
            - "/tmp:/tmp"
        environment:
            - NODE_ENV=development
        ports:
            - "9009:9009"
        working_dir: /app
        user: "${UID}:${GID}"

    front:
        environment:
            - REACT_APP_API_URL=http://localhost:4000
            - NODE_ENV=development
            - HOME=/tmp
        ports:
            - "3000:3000"
