version: '3'

services:
    hub:
        image: selenium/hub:2.53.0

    chrome:
        image: selenium/node-chrome:2.53.0
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
        depends_on:
            - hub
        links:
            - hub
            - front
            - api

    chromedebug:
        image: selenium/node-chrome-debug:2.53.0
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
        links:
            - hub
            - front
            - api
        ports:
            - 5900:5900

    test-e2e:
        image: node:9
        links:
            - hub
            - front
            - api
        depends_on:
            - hub
            - chrome
        environment:
            NODE_ENV: test
        command: yarn run test-e2e
        volumes:
            - ./front:/app
        working_dir: /app

    front:
        image: node:9
        command: 'yarn run start-web'
        volumes:
            - '.:/app'
            - '/tmp:/tmp'
        environment:
            - HOME=/tmp
            - REACT_APP_API_URL=http://api:4000
            - NODE_ENV=development
        working_dir: /app/front
        user: '${UID}:${GID}'

    api:
        command: yarn run start-dev
        depends_on:
            - db
            - maildev
        environment:
            - NODE_ENV=test
            - JWT_SECRET_KEY=jwtsecret
            - POSTGRES_DATABASE=reaction-rapide-e2e
            - API_PREFIX_URL=
            - SMTP_HOST=maildev
            - SMTP_PORT=25
            - SMTP_IGNORE_TLS=true
            - SMTP_USER=

    db:
        volumes:
            - amnesty-postgres-data:/var/lib/postgresql/data
        user: '${UID}:${GID}'
        environment:
            - NODE_ENV=test
            - POSTGRES_USER=amnesty
            - POSTGRES_PASSWORD=amnesty
            - POSTGRES_DB=reaction-rapide-e2e
            - PGDATA=/var/lib/postgresql/data/amnesty-e2e

    maildev:
        image: djfarrelly/maildev

volumes:
    amnesty-postgres-data: {}
