version: '3'

services:
    api:
        environment:
            - NODE_ENV=test
        volumes:
            - "./var/data-test:/var/lib/postgresql/data/"

    db:
        volumes:
            - "./var/data-test:/var/lib/postgresql/data/"
            - "/etc/passwd:/etc/passwd:ro"
        environment:
            - POSTGRES_USER=amnesty
            - POSTGRES_PASSWORD=amnesty
            - POSTGRES_DB=reaction-rapide-test
