import Head from 'next/head'
import { GetServerSideProps } from 'next'

import getPool from '@/utils/dbpool';
import FrontLayout from "@/components/FrontLayout";
import Story from '@/components/urgentActions/story/Story';

export const getServerSideProps: GetServerSideProps = async (context) => {

  const {slug, step = 0} = context.query;

  if(!slug) {
    return {
      notFound: true,
    }
  }

  const result = await getPool().query({
    text: `SELECT 
        id,
        title,
        story,
        call_to_action,
        email_thank,
        end_thank,
        slug,
        register,
        campaign_code,
        origin_code,
        is_default,
        message,
        social_metadata,
        response_count
      FROM urgent_action
      WHERE slug = $1;`,
    values: [slug],
})

if(!result.rows.length) {
  return {
    notFound: true,
  }
}

  return {
    props: { action: result.rows[0], step },
  }
}

export default function UrgentAction({ action, step }: { action: any, step: any }) {
  return (
    <>
      <Head>
        <title>Action Urgente - { action.title }</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FrontLayout>
            <Story // @ts-ignore
                story={action.story}
                step={step}
                callToAction={action.call_to_action}
                responseCount={action.response_count}
                auId={action.id}
            />
      </FrontLayout>
    </>
  )
}
