import Head from 'next/head'
import { GetServerSideProps } from 'next'

import getPool from '@/utils/dbpool';

export const getServerSideProps: GetServerSideProps = async (context) => {

  console.log(context.query.slug);

  const result = await getPool().query({
    text: `SELECT 
        id,
        title,
        story,
        call_to_action,
        email_thank,
        end_thank,
        slug,
        register,
        campaign_code,
        origin_code,
        is_default,
        message,
        social_metadata,
        response_count
      FROM urgent_action
      WHERE slug = $1;`,
    values: [context.query.slug],
})
console.log(result.rows.length);
if(!result.rows.length) {
  return {
    notFound: true,
  }
}

  return {
    props: { action: result.rows[0]},
  }
}

export default function UrgentAction({ action }: { action: any }) {
  return (
    <>
      <Head>
        <title>Action Urgente</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Action urgente { action.title } </h1>
    </>
  )
}
