name: 🚀 Checks
on:
    push:
        branches:
            - master
    pull_request: {}
permissions:
    actions: write
    contents: write

jobs:
    lint:
        if: ${{ false }}
        name: ⬣ ESLint
        runs-on: ubuntu-latest
        steps:
            - name: 🛑 Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1

            - name: 📥 Download deps api
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: api

            - name: 📥 Download deps front
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: front

            - name: 📥 Download deps admin
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: admin

            - name: 🔬 Lint
              uses: wearerequired/lint-action@v2
              with:
                  eslint: true
                  prettier: true

    typecheck:
        if: ${{ false }}
        name: ʦ TypeScript
        runs-on: ubuntu-latest
        steps:
            - name: 🛑 Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1

            - name: 📥 Download deps api
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: api

            - name: 📥 Download deps front
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: front

            - name: 📥 Download deps admin
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: admin

            - name: 🔎 Type check
              run: make typecheck

    test:
        name: 🧪 Test
        runs-on: ubuntu-latest
        steps:
            - name: 🛑 Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1

            - name: 📥 Download deps api
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: api

            - name: 📥 Download deps front
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: front

            - name: 📥 Download deps admin
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: admin

            - name: 🔎 Run Test
              run: make test-unit

    test-e2e:
        name: 🔗 Test e2e
        runs-on: ubuntu-latest
        steps:
            - name: 🛑 Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1

            - name: 📥 Download deps api
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: api

            - name: 📥 Download deps front
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: front

            - name: 📥 Download deps admin
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: admin

            - name: 🔎 Run Test e2e
              run: make test-e2e

    build:
        name: 🛠️ Build
        runs-on: ubuntu-latest
        steps:
            - name: 🛑 Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1

            - name: 📥 Download deps api
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: api

            - name: 📥 Download deps front
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: front

            - name: 📥 Download deps admin
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: admin

            - name: 🛠️ Build front
              run: make build-front

            - name: 🛠️ Build api
              run: make build-api

            - name: 🛠️ Build admin
              run: make build-admin

    deploy:
        name: 🚀 Deploy
        needs: [test, test-e2e, build]
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - name: 🛑 Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1

            - name: 📥 Download deps api
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: api

            - name: 📥 Download deps front
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: front

            - name: 📥 Download deps admin
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: admin

            - name: 🕵️‍♂️ Installing ssh
              run: mkdir ~/.ssh && cho $KEY >> ~/.ssh/amnesty-staging
              env:
                  DEV_ENV_FILE: ${{secrets.KEY}}

            - name: 🚀 Deploy
              run: make deploy-staging
